---
stages:
  - triggers

# Build, test, and generate resources for the KeyCloak plugin.
plugin_pipeline:
  stage: triggers
  trigger:
    include: "/.gitlab/ci/maven_jobs.yml"
  rules:
    - changes:
        - "reCaptcha-auth-flow/*"

# Build, test, and generate resources for the KeyCloak theme.
theme_pipeline:
  stage: triggers
  trigger:
    include: "/.gitlab/ci/theme_jobs.yml"
  rules:
    - changes:
        - "reCaptcha-theme/*"

# A release is only possible from a semantic version tag,
# and must be triggered manually, from the GitLab CI web UI.
release_pipeline:
  stage: triggers
  trigger:
    include: "/.gitlab/ci/release_pipeline.yml"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/'
      when: manual
    - when: never
