---
stages:
  - triggers

variables:
  FILENAME_RECAPTCHA_PLUGIN_THEME: "reCaptcha-theme.tar.gz"
  FILENAME_RECAPTCHA_PLUGIN_JAR: "reCaptcha-auth-flow.jar"

# Build, test, and generate resources for the KeyCloak plugin.
plugin_pipeline:
  stage: triggers
  trigger:
    include: "/.gitlab/ci/maven_pipeline.yml"
  rules:
    - changes:
        - "reCaptcha-auth-flow/*"

# Build, test, and generate resources for the KeyCloak theme.
theme_pipeline:
  stage: triggers
  trigger:
    include: "/.gitlab/ci/theme_pipeline.yml"
  rules:
    - changes:
        - "reCaptcha-theme/*"

# A release can be triggered manually, from the GitLab CI web UI.
release_pipeline:
  stage: triggers
  trigger:
    include: "/.gitlab/ci/release_pipeline.yml"
  rules:
    - when: manual
