---
stages:
  - infrastructure
  - release
  - documentation


include:
  - project: univention/dist/docker-services
    file: kaniko.yml

# Handles setup and updates of the environment `production`.
setup_environment_production:
  stage: infrastructure
  trigger:
    include: "/.gitlab/ci/environment/environment_pipeline.yml"
  variables:
    TARGET_ENVIRONMENT: "production"
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

# Handles setup and updates of the environment `staging`.
setup_environment_staging:
  stage: infrastructure
  trigger:
    include: "/.gitlab/ci/environment/environment_pipeline.yml"
  variables:
    TARGET_ENVIRONMENT: "staging"
  rules:
    - if: $CI_COMMIT_BRANCH == 'development'

# Handles setup and updates of the environment for an MR commit, based on the merge request numerical ID.
setup_environment_mr:
  stage: infrastructure
  trigger:
    include: "/.gitlab/ci/environment/environment_pipeline.yml"
  variables:
      TARGET_ENVIRONMENT: "mr-${CI_MERGE_REQUEST_IID}"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# A GitLab Release is done upon semantic version tag push.
release_pipeline:
  stage: release
  trigger:
    include: "/.gitlab/ci/release/release_pipeline.yml"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/'

build-keycloak-handler-job:
  stage: release
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: "handler"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-handler"
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE-cache"
  after_script:
    - docker images --all
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

build-keycloak-proxy-job:
  stage: release
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: "proxy"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-proxy"
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE-cache"
  after_script:
    - docker images --all
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

# Generates documentation artifacts for the current commit.
# This pipeline is based on the documentation and coockiecutter project generator at:
# https://git.knut.univention.de/univention/documentation/docs-template/-/tree/main/
documentation_pipeline:
  stage: documentation
  trigger:
    include: "/.gitlab/ci/documentation/documentation_pipeline.yml"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# [EOF]
