---
stages:
  - build
  - release

# Build, test, and generate resources for the KeyCloak plugin.
plugin_pipeline:
  stage: build
  trigger:
    include: "/.gitlab/ci/plugin_pipeline.yml"
  rules:
    - changes:
        - "reCaptcha-auth-flow/*"

# Build, test, and generate resources for the KeyCloak theme.
theme_pipeline:
  stage: build
  trigger:
    include: "/.gitlab/ci/theme_pipeline.yml"
  rules:
    - changes:
        - "reCaptcha-theme/*"

# This release job can be triggered manually, from the GitLab CI web UI.
release_pipeline:
  stage: release
  trigger:
    include: "/.gitlab/ci/release_pipeline.yml"
  rules:
    - when: manual
