---
stages:
  - infrastructure
  - release
  - documentation

# Handles setup and provisioning of the environment `production`.
setup_environment_production:
  stage: infrastructure
  trigger:
    include: "/.gitlab/ci/environment/environment_pipeline.yml"
  variables:
    TARGET_ENVIRONMENT: "production"
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

# Handles setup and provisioning of the environment `staging`.
setup_environment_staging:
  stage: infrastructure
  trigger:
    include: "/.gitlab/ci/environment/environment_pipeline.yml"
  variables:
    TARGET_ENVIRONMENT: "staging"
  rules:
    - if: $CI_COMMIT_BRANCH == 'development'

# Handles setup and provisioning of the environment for an MR commit, based on the merge request numerical ID.
setup_environment_mr:
  stage: infrastructure
  trigger:
    include: "/.gitlab/ci/environment/environment_pipeline.yml"
  variables:
      TARGET_ENVIRONMENT: "mr-${CI_MERGE_REQUEST_IID}"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# A GitLab Release is done upon semantic version tag push.
release_pipeline:
  stage: release
  trigger:
    include: "/.gitlab/ci/release/release_pipeline.yml"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/'

# The Docker images for `proxy` and `handler` are published upon semantic version tag push as well.
docker_pipeline:
  stage: release
  trigger:
    include: "/.gitlab/ci/docker/docker_pipeline.yml"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/'

# Generates documentation artifacts upon semantic version tag push.
documentation_pipeline_semantic_version:
  stage: documentation
  trigger:
    include: "/.gitlab/ci/documentation/documentation_pipeline.yml"
  variables:
    TARGET_VERSION: "$CI_COMMIT_TAG"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/'

# Generates documentation artifacts for an MR commit, based on the merge request numerical ID.
documentation_pipeline_mr:
  stage: documentation
  trigger:
    include: "/.gitlab/ci/documentation/documentation_pipeline.yml"
  variables:
    DOC_TARGET_VERSION: "mr-${CI_MERGE_REQUEST_IID}"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'