---
variables:
  SOUVAP_API_V4_URL: https://gitlab.souvap-univention.de/api/v4
  SOUVAP_HELM_ACCESS_USER: gitlab-ci-knut
  SOUVAP_DOCKER_ACCESS_USER: gitlab-ci-knut
  # TODO: Adjust repository configuration and then remove this line
  SOUVAP_DOCKER_ACCESS_TOKEN: ${SOUVAP_REGISTRY_TOKEN}
  SOUVAP_HELM_PROJECT_ID: 77
  SOUVAP_REGISTRY_HOST: registry.souvap-univention.de
  SOUVAP_REGISTRY_PATH: souvap/tooling/images/keycloak-extensions
  SOUVAP_REGISTRY_REPO: ${SOUVAP_REGISTRY_HOST}/${SOUVAP_REGISTRY_PATH}

stages:
  - lint
  - test
  - package
  - publish
  - release

include:
  - project: univention/dist/docker-services
    file: kaniko.yml
  - project: univention/customers/dataport/upx/common-ci
    file:
      - defaults/souvap-workflow.yaml
      - templates/souvap.yaml
      - jobs/package-and-publish-helm-charts.yaml


build-keycloak-handler-job:
  stage: release
  needs: []
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: "handler"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-handler"
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE-cache"
  after_script:
    - docker images --all

push-image-souvap-handler-job:
  stage: release
  needs:
    - job: build-keycloak-handler-job
  extends: .push-image-souvap
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-handler"
    SOUVAP_IMAGE_NAME: "keycloak-handler"

build-keycloak-proxy-job:
  stage: release
  needs: []
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: "proxy"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-proxy"
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE-cache"
  after_script:
    - docker images --all

push-image-souvap-proxy-job:
  stage: release
  needs:
    - job: build-keycloak-proxy-job
  extends: .push-image-souvap
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-proxy"
    SOUVAP_IMAGE_NAME: "keycloak-proxy"

lint-helm-chart:
  stage: lint
  needs: []
  image:
    name: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/alpine/helm:3.10.2"
    entrypoint: [""]
  script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm dependency build helm/keycloak-extensions
    - helm lint helm/keycloak-extensions --strict


tests:
  stage: test
  needs: []
  trigger:
    include: "/.gitlab/ci/tests/docker_tests.yml"
    strategy: depend


pre-commit:
  stage: lint
  needs: []
  image:
    name: "gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest"
    entrypoint: [""]
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
    PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
  script:
    - git config --global --add safe.directory /builds/univention/customers/dataport/upx/pocs/keycloak-extensions
    - pre-commit run --all-files
