# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.12.0"
    file:
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-souvap.yaml"
      - "jobs/package-and-publish-helm-charts-souvap.yaml"

variables:
  SOUVAP_HELM_PROJECT_ID: 77

lint-pre-commit:
  before_script:
    - "helm repo add bitnami https://charts.bitnami.com/bitnami"

.build-matrix: &build-matrix
  - IMAGE_NAME: "keycloak-handler"
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR/handler"
  - IMAGE_NAME: "keycloak-proxy"
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR/proxy"

.publish-matrix: &publish-matrix
  - IMAGE_NAME:
      - "keycloak-handler"
      - "keycloak-proxy"

container-build:
  parallel:
    matrix: *build-matrix
  variables:
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE/${IMAGE_NAME}-cache"
    DOCKERFILE_PATH: "${CI_PROJECT_DIR}/docker/${IMAGE_NAME}/Dockerfile"

container-generate-sbom:
  parallel:
    matrix: *build-matrix

container-sign:
  parallel:
    matrix: *build-matrix

container-security-scan:
  parallel:
    matrix: *build-matrix

push-image-souvap:
  parallel:
    matrix: *publish-matrix

container-sign-souvap:
  parallel:
    matrix: *publish-matrix

lint-helm-chart:
  stage: "lint"
  needs: []
  image:
    name: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/alpine/helm:3.10.2"
    entrypoint: [""]
  script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm dependency build helm/keycloak-extensions
    - helm lint helm/keycloak-extensions --strict

tests:
  stage: "test"
  needs: []
  trigger:
    include: "/.gitlab/ci/tests/docker_tests.yml"
    strategy: depend
...
