---
stages:
  - build
  - release

build_jar:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_jar.yml"

build_theme:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_theme.yml"

release_job:
  stage: release
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    VERSION_MAJOR:
      value: "0"
      description: "The major version number."
    VERSION_MINOR:
      value: "1"
      description: "The minor version number."
    VERSION_PATCH:
      value: "0"
      description: "The patch version number."
  trigger:
    include: "/.gitlab/ci/release.yml"
  when: manual
