---
stages:
  - build
  - release

build_jar:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_jar.yml"
  rules:
    - changes:
        - "reCaptcha-auth-flow/*"

build_theme:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_theme.yml"
  rules:
    - changes:
        - "reCaptcha-theme/*"

release_job:
  stage: release
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    DIST_FOLDER_NAME: "dist"
    VERSION_TAG: "v1.2.3"
  trigger:
    include: "/.gitlab/ci/release.yml"
  needs:
    - "build_jar"
    - "build_theme"
  when: manual
