---
stages:
  - build
  - release

build_jar:
  # Taken from: https://gitlab.com/gitlab-org/gitlab-ci-yml/-/blob/master/Maven.gitlab-ci.yml
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # Uses the pom.xml file as cache key, so that when dependencies change, the cache gets invalidated.
  cache:
    - key:
        files:
          - "reCaptcha-auth-flow/pom.xml"
      paths:
        - ".m2/repository"
  stage: build
  image: "artifacts.knut.univention.de/dockerhub_proxy_cache/library/maven:3.8.6-openjdk-18"
  script:
    - cd reCaptcha-auth-flow
    - mvn clean install
  artifacts:
    paths:
      - "reCaptcha-auth-flow/target/reCaptcha-auth-flow.jar"

build_theme:
  stage: build
  image: "artifacts.knut.univention.de/dockerhub_proxy_cache/library/busybox"
  script:
    - 'tar -cvzf reCaptcha-theme.tar.gz ./reCaptcha-theme'
  artifacts:
    paths:
      - "reCaptcha-theme.tar.gz"

release_job:
  stage: release
  variables:
    UPSTREAM_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include: "/.gitlab/ci/release.yml"
  when: manual