---
variables:
  SOUVAP_API_V4_URL: https://gitlab.souvap-univention.de/api/v4
  SOUVAP_HELM_ACCESS_USER: gitlab-ci-knut
  SOUVAP_HELM_PROJECT_ID: 77
  SOUVAP_REGISTRY_HOST: registry.souvap-univention.de
  SOUVAP_REGISTRY_PATH: souvap/tooling/images/keycloak-extensions
  SOUVAP_REGISTRY_REPO: ${SOUVAP_REGISTRY_HOST}/${SOUVAP_REGISTRY_PATH}
  SOUVAP_REGISTRY_USER: gitlab-ci-knut

stages:
  - test
  - release

include:
  - project: univention/dist/docker-services
    file: kaniko.yml

.push-image-souvap:
  variables:
    GIT_STRATEGY: none
  image: artifacts.knut.univention.de/dockerhub_proxy_cache/library/docker:20.10.12
  services:
    - name: docker-registry.knut.univention.de/ucs/docker:dind
      alias: docker
  before_script:
    # derived from the .kaniko_pre to define the IMAGE_TAG and IMAGE_VERSION
    - |-
      if [ "${CI_COMMIT_REF_NAME:-}" = "${CI_DEFAULT_BRANCH:-}" ]; then
        VERSION="latest"
      elif [ -n "${CI_COMMIT_TAG:-}" ]; then
        NOSLASH=$(echo "${CI_COMMIT_TAG:-}" | tr -s / -)
        SANITIZED="${NOSLASH//[^a-zA-Z0-9\-\.]/}"
        VERSION="$SANITIZED"
      else
        NOSLASH=$(echo "${CI_COMMIT_REF_NAME:-}" | tr -s / -)
        SANITIZED="${NOSLASH//[^a-zA-Z0-9\-]/}"
        VERSION="branch-$SANITIZED"
      fi
      if [ ! -z "${IMAGE_TAG:-}" ]; then
        IMAGE_TAG="${CI_REGISTRY_IMAGE:-}:$VERSION"
      fi
    - echo "IMAGE_TAG=$IMAGE_TAG" | tee -a ./.env
    - echo "IMAGE_VERSION=$VERSION" | tee -a ./.env
  script:
    # Load variables from before_script
    - . ./.env
    - SOUVAP_IMAGE_TAG="${SOUVAP_REGISTRY_REPO}/${SOUVAP_IMAGE_NAME}:${IMAGE_VERSION}"
    - echo "logging in with CI_JOB_TOKEN"
    - echo "${CI_JOB_TOKEN}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    - 'echo "pulling image: ${IMAGE_TAG}"'
    - docker pull "${IMAGE_TAG}"
    - 'echo "tagging image: ${SOUVAP_IMAGE_TAG}"'
    - docker tag "${IMAGE_TAG}" "${SOUVAP_IMAGE_TAG}"
    # Use SouvAP-Repo-Access-Token to push image
    - echo "${SOUVAP_REGISTRY_TOKEN}" | docker login --username "${SOUVAP_REGISTRY_USER}" --password-stdin "${SOUVAP_REGISTRY_HOST}"
    - docker push "${SOUVAP_IMAGE_TAG}"

build-keycloak-handler-job:
  stage: release
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: "handler"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-handler"
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE-cache"
  after_script:
    - docker images --all
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

push-image-souvap-handler-job:
  stage: release
  needs:
    - job: build-keycloak-handler-job
  extends: .push-image-souvap
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-handler"
    SOUVAP_IMAGE_NAME: "keycloak-handler"

build-keycloak-proxy-job:
  stage: release
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: "proxy"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-proxy"
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE-cache"
  after_script:
    - docker images --all
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

push-image-souvap-proxy-job:
  stage: release
  needs:
    - job: build-keycloak-proxy-job
  extends: .push-image-souvap
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-proxy"
    SOUVAP_IMAGE_NAME: "keycloak-proxy"

lint-helm-chart:
  stage: release
  image:
    name: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/alpine/helm:3.10.2"
    entrypoint: [""]
  script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm dependency build helm
    - helm lint helm --strict

package-helm-chart:
  stage: release
  needs: []
  artifacts:
    paths:
      - "packages/*.tgz"
  image:
    name: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/alpine/helm:3.10.2"
    entrypoint: [""]
  script:
    - 'if [ -z "${RELEASE_VERSION}" ]; then exit 0; fi'
    - "helm repo add bitnami https://charts.bitnami.com/bitnami"
    - "helm package --version ${RELEASE_VERSION} --destination ./packages --dependency-update helm"
  variables:
    # TODO: Extract the release information from Git.
    # Compare: https://gitlab.souvap-univention.de/souvap/tooling/charts/openproject-helm-chart/-/blob/souvap/.gitlab-ci.yml#L25
    RELEASE_VERSION: "0.1.0"

publish-helm-chart:
  stage: release
  dependencies:
    - "package-helm-chart"
  needs:
    - "package-helm-chart"
  image: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/curlimages/curl:latest"
  script:
    - 'if [ -z "${RELEASE_VERSION}" ]; then exit 0; fi'
    - |
      for _filename in `find packages -type f`;
      do
        curl \
        --request "POST" \
        --user "${SOUVAP_HELM_ACCESS_USER}:${SOUVAP_HELM_ACCESS_TOKEN}" \
        --form "chart=@$_filename" \
        "${SOUVAP_API_V4_URL}/projects/${SOUVAP_HELM_PROJECT_ID}/packages/helm/api/stable/charts";
      done
  variables:
    GIT_STRATEGY: "none"
    # TODO: Extract the release information from Git.
    # Compare: https://gitlab.souvap-univention.de/souvap/tooling/charts/openproject-helm-chart/-/blob/souvap/.gitlab-ci.yml#L25
    RELEASE_VERSION: "0.1.0"

tests:
  stage: test
  trigger:
    include: "/.gitlab/ci/tests/docker_tests.yml"
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH # pipelines can't be created for MR, so sticking with only branch
