---
stages:
  - infrastructure
  - release

# Handles setup and updates of the environment `production`.
setup_environment_production:
  stage: infrastructure
  trigger:
    include: "/.gitlab/ci/environment/environment_pipeline.yml"
  variables:
    TARGET_ENVIRONMENT: "production"
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always
    - when: never

# Handles setup and updates of the environment `staging`.
setup_environment_staging:
  stage: infrastructure
  trigger:
    include: "/.gitlab/ci/environment/environment_pipeline.yml"
  variables:
    TARGET_ENVIRONMENT: "staging"
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
      when: always
    - when: never

# Handles setup and updates of the environment for this commit, based on the CI_COMMIT_REF_SLUG.
setup_environment_commit:
  stage: infrastructure
  trigger:
    include: "/.gitlab/ci/environment/environment_pipeline.yml"
  variables:
      TARGET_ENVIRONMENT: "commit-${CI_COMMIT_REF_SLUG}"
  rules:
    - if: $CI_COMMIT_BRANCH != 'develop' && $CI_COMMIT_BRANCH != 'main'
      when: manual
    - when: never

# A release is only possible from a semantic version tag,
# and must be triggered manually, from the GitLab CI web UI.
release_pipeline:
  stage: release
  trigger:
    include: "/.gitlab/ci/release/release_pipeline.yml"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/'
      when: always
    - when: never
