---
stages:
  - build
  - release

build_jar:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_jar.yml"

build_theme:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_theme.yml"

# This whole job only runs when a tag is added that adheres to semantic versioning.
# For more info on Semantic Versioning, see: https://semver.org/
release_job:
  stage: release
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  trigger:
    include: "/.gitlab/ci/release.yml"