---
stages:
  - build
  - release

workflow:
  rules:
    - if: '$CI_COMMIT_TAG != null'
      variables:
        VERSION_TAG: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_TAG == null'
      variables:
        VERSION_TAG: $CI_COMMIT_SHORT_SHA

build_jar:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_jar.yml"

build_theme:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_theme.yml"

release_job:
  stage: release
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include: "/.gitlab/ci/release.yml"
  when: manual