---
stages:
  - build
  - release

build_jar:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_jar.yml"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

build_theme:
  stage: build
  trigger:
    include: "/.gitlab/ci/build_theme.yml"
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

release_package:
  stage: release
  variables:
    UPSTREAM_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include: "/.gitlab/ci/release.yml"
  when: manual