---
stages:
  - test
  - release


include:
  - project: univention/dist/docker-services
    file: kaniko.yml


# A release is only possible from a semantic version tag,
# and must be triggered manually, from the GitLab CI web UI.
release_pipeline:
  stage: release
  trigger:
    include: "/.gitlab/ci/release/release_pipeline.yml"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/'
      when: always
    - when: never

build-keycloak-handler-job:
  stage: release
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: "handler"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-handler"
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE-cache"
  after_script:
    - docker images --all
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

build-keycloak-keycloak-job:
  stage: release
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: "keycloak"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-keycloak"
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE-cache"
  after_script:
    - docker images --all
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

build-keycloak-proxy-job:
  stage: release
  extends: .kaniko
  variables:
    KANIKO_BUILD_CONTEXT: "proxy"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/keycloak-proxy"
    KANIKO_ARGS: "--skip-unused-stages=true --cache=true --cache-repo=$CI_REGISTRY_IMAGE-cache"
  after_script:
    - docker images --all
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

tests:
  stage: test
  trigger:
    include: "/.gitlab/ci/tests/docker_tests.yml"
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH  # pipelines can't be created for MR, so sticking with only branch
