# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

repos:
  - repo: "https://github.com/compilerla/conventional-pre-commit"
    rev: "v3.0.0"
    hooks:
      - id: "conventional-pre-commit"
        stages: ["commit-msg"]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        name: autopep8
        description: Check that python code style follows pep8
        language: python
        types:
          - python
        args:
          - -i
        require_serial: false
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.56.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        name: eslint
        description: Check NodeJS syntax and enforce style.
        args: [--fix]
        additional_dependencies:
          - eslint@8.37.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
        name: check for merge conflicts
        description: Checks for files that contain merge conflict strings.
        entry: check-merge-conflict
        types: [text]
      - id: end-of-file-fixer
        name: fix end of files
        description: Ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
      - id: trailing-whitespace
        name: trim trailing whitespace
        description: Trims trailing whitespace.
        entry: trailing-whitespace-fixer
      - id: check-executables-have-shebangs
        name: check that executables have shebangs
        description: Ensures that (non-binary) executables have a shebang.
        entry: check-executables-have-shebangs
        language: python
        types: [text, executable]
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.12.0
    hooks:
      - id: helm-docs
        args: []
        description: Uses 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file, and inserts the result into a corresponding 'README.md' file.
        entry: git-hook/helm-docs
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
        language: script
        name: Helm Docs
        require_serial: true
        always_run: true
      - id: helm-docs-built
        args: []
        description: Uses auto built 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file, and inserts the result into a corresponding 'README.md' file.
        entry: helm-docs
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
        language: golang
        name: Helm Docs Built
        require_serial: true
  - repo: "https://git.knut.univention.de/univention/dist/pre-commit-hooks/addlicense"
    rev: "v1.0.1"
    hooks:
      - id: "addlicense"
        name: "Check or add license headers to files"
...
