version: "3.7"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.0
    # image: keycloak:captcha
    # build: ./keycloak
    command: start-dev --http-enabled=true
    ports:
      - 5050:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=univention
      - PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY=edge
      - KEYCLOAK_LOGLEVEL=ALL
      - ROOT_LOGLEVEL=ALL

  proxy:
    container_name: keycloak-extensions-proxy
    image: keycloak-extensions-proxy:develop
    build: ./proxy
    ports:
      - 8181:8181
    depends_on:
      - keycloak
      - database
      - handler
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      LOG_LEVEL: debug
      # Database
      POSTGRES_USER: postgres
      POSTGRES_HOST: database
      POSTGRES_DATABASE_NAME: handler
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432

  handler:
    container_name: keycloak-extensions-handler
    image: keycloak-extensions-handler:develop
    build: ./handler
    depends_on:
      # - keycloak
      - database
    environment:
      # Keycloak
      KC_AUTH_URL: http://keycloak:8080/admin
      KC_USER: admin
      KC_PASS: univention
      KC_REALM: master
      # Database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE_NAME: handler
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      # Logging
      LOG_LEVEL: DEBUG
      # Configuration
      FAILED_ATTEMPTS_FOR_IP_BLOCK: 7
      FAILED_ATTEMPTS_FOR_DEVICE_BLOCK: 5
      FAILED_ATTEMPTS_FOR_CAPTCHA_TRIGGER: 3
      EVENTS_RETENTION_MINUTES: 1
      AUTO_EXPIRE_RULE_IN_MINS: 1
      DEVICE_PROTECTION_ENABLE: "True"
      IP_PROTECTION_ENABLE: "True"
      CAPTCHA_PROTECTION_ENABLE: "True"
      # Email
      SMTP_SERVER: mail.example.org
      SMTP_PORT: 587
      SENDER_EMAIL: univention@example.org
      SENDER_EMAIL_PASSWORD: somepassword

  database:
    container_name: keycloak-extensions-postgres
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: handler

  e2e-tests:
    container_name: e2e-tests
    image: e2e-tests:develop
    build: ./tests/e2e
    depends_on:
      - keycloak
      - database
      - handler
      - proxy
    environment:
      PROXY_BASE_URL: http://proxy:8181
