version: "3.7"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.0
    command: start-dev --http-enabled=true
    ports:
      - 5050:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=univention
      - PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY=edge
      - KEYCLOAK_LOGLEVEL=ALL
      - ROOT_LOGLEVEL=ALL

  proxy:
    container_name: keycloak-extensions-proxy
    image: keycloak-proxy:develop
    build: ./node-proxy
    ports:
      - 8181:8181
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      LOG_LEVEL: debug
      # Database
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: actions
      DB_PASSWORD: postgres
      DB_PORT: 5432
      # Email
      TARGET_EMAILS: test@example.org
      SENDER_MAIL: test@example.org
      SMTP_SERVER: mail.example.org
      SMTP_PASSWORD: example_password
      ADMIN_MAIL: admin@example.org
      API_SECRET: someapikey
      MAIL_BACKOFF_TIME: 5

  handler:
    container_name: keycloak-extensions-handler
    image: keycloak-handler:develop
    build: ./handler
    depends_on:
      - keycloak
    environment:
      # Keycloak
      KC_AUTH_URL: http://localhost:5050/admin
      KC_USER: admin
      KC_PASS: admin
      KC_REALM: master
      # Logging
      LOG_LEVEL: debug
      # Configuration
      DAILED_ATTEMPTS_FOR_IP_BLOCK: 7
      DAILED_ATTEMPTS_FOR_DEVICE_BLOCK: 5
      DAILED_ATTEMPTS_FOR_CAPTCHA_TRIGGER: 3
      EVENTS_RETENTION_PERIOD: 10
