sonar.projectKey=univention_dev_projects_keycloak_keycloak-extensions_9124d33d-0e52-481e-a693-378352298359
sonar.qualitygate.wait=true
sonar.python.version=3.11
sonar.links.homepage=https://git.knut.univention.de/univention/dev/projects/keycloak/keycloak-extensions
sonar.links.issue=https://git.knut.univention.de/univention/dev/internal/team-nubus/-/issues
sonar.links.scm=https://git.knut.univention.de/univention/dev/projects/keycloak/keycloak-extensions
sonar.exclusions=keycloak/*
