---
# For documentation on the use of this role, and default variables,
# See: https://github.com/univention/ansible-roles#rolesucs_joinreadmemd
- name: "UCS join"
  ansible.builtin.include_role:
    name: "univention.ucs_roles.ucs_join"
  vars:
    ucs_join_hide_logging: False
    ucs_join_basedn: "{{ basedn }}"
    ucs_join_domain_name: "{{ domain_name }}"
    ucs_join_hostname: "{{ host_name }}"
    ucs_join_admin_user_name: "{{ admin_user_name }}"
    ucs_join_root_password: "{{ root_password }}"
    network_config_static_ip_config: "{{ server_ip }}/24"
  tags:
    - "ucs_join"
