---

apiVersion: v2
type: application
name: keycloak-extensions
description: A Helm chart for Kubernetes with its extensions
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: 0.1.0

# Keycloak version
appVersion: "21.0.1"

dependencies:
  - name: "common"
    repository: "https://charts.bitnami.com/bitnami"
    version: "^2.12.0"
  - name: "handler"
    repository: "file://./charts/handler"
    version: "0.1.0"
  - name: "postgresql"
    repository: "https://charts.bitnami.com/bitnami"
    version: "^12.12.9"
    condition: postgresql.enabled
  - name: "proxy"
    repository: "file://./charts/proxy"
    version: "0.1.0"

...
