# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
apiVersion: v2
type: application
name: keycloak-extensions
description: A Helm chart for Kubernetes with its extensions
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: 0.1.0

# Keycloak version
appVersion: "21.0.1"

dependencies:
  - name: "common"
    repository: "https://charts.bitnami.com/bitnami"
    version: "^2.2.2"
  - name: "handler"
    repository: "file://./charts/handler"
    version: "0.1.0"
  - name: "postgresql"
    repository: "https://charts.bitnami.com/bitnami"
    version: "^12.2.2"
    condition: postgresql.enabled
  - name: "proxy"
    repository: "file://./charts/proxy"
    version: "0.1.0"
