# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
global:
  certManagerIssuer: "linting-issuer"

postgresql:
  connection:
    host: "linting-host"
    port: "linting-port"
  auth:
    username: "linting-username"
    password: "linting-password"
    database: "linting-database"

keycloak:
  auth:
    username: "linting-adminUsername"
    password: "linting-adminPassword"
    realm: "linting-realm"
  connection:
    host: "linting-host"

proxy:
  ingress:
    ingressClassName: "linting-ingress"
    tls:
      secretName: "linting-secret"
