# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
global:
  certManagerIssuer: "linting-issuer"

postgresql:
  connection:
    host: "linting-host"
    port: "linting-port"
  auth:
    username: "linting-username"
    database: "linting-database"
    existingSecret:
      name: "custom-postgres-credentials"
      keyMapping:
        password: "custom-password"

keycloak:
  auth:
    username: "linting-adminUsername"
    realm: "linting-realm"
    existingSecret:
      name: "custom-keycloak-credentials"
      keyMapping:
        adminPassword: "admin_password"
  connection:
    host: "linting-host"

proxy:
  ingress:
    ingressClassName: "linting-ingress"
    tls:
      secretName: "linting-secret"
