# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
global:
  certManagerIssuer: "linting-issuer"

postgresql:
  connection:
    host: "linting-host"
    port: "linting-port"
  auth:
    username: "stub-values-username"
    database: "linting-database"
    password: "stub-value"

keycloak:
  auth:
    username: "stub-values-username"
    realm: "linting-realm"
    password: "stub-value"
  connection:
    host: "linting-host"

proxy:
  ingress:
    ingressClassName: "linting-ingress"
    tls:
      secretName: "linting-secret"
  appConfig:
    captcha:
      captchaSiteKey: "stub-values-site-key"
      captchaSecretKey: "stub-values-secret-key"

handler:
  service:
    enabled: true
    type: "ClusterIP"
    # -- Additional custom annotations to add to service.
    additionalAnnotations: {}
    ports:
      http:
        containerPort: 8181
        port: 8181
        protocol: "TCP"

    sessionAffinity:
      enabled: false
      timeoutSeconds: 10800

  appConfig:
    captchaProtectionEnable: true

smtp:
  auth:
    username: "stub-values-username"
    password: "stub-value"
