#!/bin/bash

# shellcheck source=/dev/null
[ -e /usr/share/univention-lib/ucr.sh ] && . /usr/share/univention-lib/ucr.sh


ACTION="$1"
APP_ID="$2"  # keycloak-extensions
APP_VERSION="$3"
ERROR_FILE="$4"



if [ -n "$action" ] && [ "$action" = "remove" ]; then
    exit 0
fi
