# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ printf "%s-handler" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-handler" (include "common.names.fullname" .)) }}
    {{- $mergedLabels := merge $uiLabels $commonLabels}}
    {{- toYaml $mergedLabels | nindent 4 }}
    {{- if .Values.handler.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.handler.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.handler.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.handler.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  KC_AUTH_URL: {{ include "keycloak-extensions.keycloak.connection.authUrl" . | quote }}
  KC_USER: {{ include "keycloak-extensions.keycloak.auth.username" . | quote }}
  KC_REALM:  {{ include "keycloak-extensions.keycloak.auth.realm" . | quote }}
  KC_USER_REALM: {{ include "keycloak-extensions.keycloak.auth.masterRealm" . | quote }}
  POSTGRES_HOST: {{ include "keycloak-extensions.postgresql.connection.host" . | quote }}
  POSTGRES_PORT: {{ include "keycloak-extensions.postgresql.connection.port" . | quote }}
  POSTGRES_USER: {{ include "keycloak-extensions.postgresql.auth.username" . | quote }}
  POSTGRES_DATABASE_NAME: {{ include "keycloak-extensions.postgresql.auth.database" . | quote }}
  LOG_LEVEL: "{{ .Values.handler.appConfig.logLevel }}"
  FAILED_ATTEMPTS_FOR_IP_BLOCK: "{{ .Values.handler.appConfig.failedAttemptsForIpBlock }}"
  FAILED_ATTEMPTS_FOR_DEVICE_BLOCK: "{{ .Values.handler.appConfig.failedAttemptsForDeviceBlock }}"
  FAILED_ATTEMPTS_FOR_CAPTCHA_TRIGGER: "{{ .Values.handler.appConfig.failedAttemptsForCaptchaTrigger }}"
  EVENTS_RETENTION_PERIOD: "{{ .Values.handler.appConfig.eventsRetentionPeriod }}"
  AUTO_EXPIRE_RULE_IN_MINS: "{{ .Values.handler.appConfig.autoExpireRuleInMins }}"
  DEVICE_PROTECTION_ENABLE: "{{ .Values.handler.appConfig.deviceProtectionEnable }}"
  IP_PROTECTION_ENABLE: "{{ .Values.handler.appConfig.ipProtectionEnable }}"
  CAPTCHA_PROTECTION_ENABLE: "{{ .Values.handler.appConfig.captchaProtectionEnable }}"
  NEW_DEVICE_LOGIN_NOTIFICATION_ENABLE: "{{ .Values.handler.appConfig.newDeviceLoginNotificationEnable }}"
  NEW_DEVICE_LOGIN_SUBJECT: "{{ .Values.handler.appConfig.newDeviceLoginSubject }}"
  SMTP_HOST: {{ include "keycloak-extensions.smtp.connection.host" . | quote }}
  SMTP_PORT: {{ include "keycloak-extensions.smtp.connection.port" . | quote }}
  SMTP_USERNAME: {{ include "keycloak-extensions.smtp.auth.username" . | quote }}
  MAIL_FROM: "{{ .Values.handler.appConfig.mailFrom }}"

...
