# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ printf "%s-proxy" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.proxy.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.proxy.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.proxy.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.proxy.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  KEYCLOAK_URL: "http://{{ required "A value for coalesce .Values.keycloak.host must be configured." (coalesce .Values.keycloak.host .Values.global.keycloak.host) }}"
  KC_AUTH_URL: "http://{{ required "A value for .Values.keycloak.host or .Values.global.keycloak.host must be configured." (coalesce .Values.keycloak.host .Values.global.keycloak.host) }}/admin"
  KC_USER: "{{ required "A value for .Values.keycloak.adminUsername or .Values.global.keycloak.adminUsername must be configured." (coalesce .Values.keycloak.adminUsername .Values.global.keycloak.adminUsername) }}"
  KC_PASS: "{{ required "A value for .Values.keycloak.adminPassword or .Values.global.keycloak.adminPassword must be configured." (coalesce .Values.keycloak.adminPassword .Values.global.keycloak.adminPassword) }}"
  KC_REALM: "{{ required "A value for .Values.keycloak.realm or .Values.global.keycloak.realm must be configured." (coalesce .Values.keycloak.realm .Values.global.keycloak.realm) }}"
  KC_USER_REALM: "{{ required "A value for .Values.keycloak.adminRealm or .Values.global.keycloak.adminRealm must be configured." (coalesce .Values.keycloak.adminRealm .Values.global.keycloak.adminRealm) }}"
  POSTGRES_HOST: "{{ required "A value for .Values.postgresql.connection.host or .Values.global.postgresql.connection.host must be configured." (coalesce .Values.postgresql.connection.host .Values.global.postgresql.connection.host) }}"
  POSTGRES_PORT: "{{ required "A value for .Values.postgresql.connection.port or .Values.global.postgresql.connection.port must be configured." (coalesce .Values.postgresql.connection.port .Values.global.postgresql.connection.port) }}"
  POSTGRES_USER: "{{ required "A value for .Values.postgresql.auth.username or .Values.global.postgresql.auth.username must be configured." (coalesce .Values.postgresql.auth.username .Values.global.postgresql.auth.username) }}"
  POSTGRES_PASSWORD: "{{ required "A value for .Values.postgresql.auth.password or .Values.global.postgresql.auth.password must be configured." (coalesce .Values.postgresql.auth.password .Values.global.postgresql.auth.password) }}"
  POSTGRES_DATABASE_NAME: "{{ required "A value for .Values.postgresql.auth.database or .Values.global.postgresql.auth.database must be configured." (coalesce .Values.postgresql.auth.database .Values.global.postgresql.auth.database) }}"
  CAPTCHA_SITE_KEY: "{{ .Values.proxy.appConfig.captchaSiteKey }}"
  CAPTCHA_SECRET_KEY: "{{ .Values.proxy.appConfig.captchaSecretKey }}"
  LOG_LEVEL: "{{ .Values.proxy.appConfig.logLevel }}"
