# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ printf "%s-proxy" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-proxy" (include "common.names.fullname" .)) }}
    {{- $mergedLabels := merge $uiLabels $commonLabels}}
    {{- toYaml $mergedLabels | nindent 4 }}
    {{- if .Values.proxy.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.proxy.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.proxy.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.proxy.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  KEYCLOAK_URL: {{ include "keycloak-extensions.keycloak.connection.baseUrl" . | quote }}
  KC_AUTH_URL: {{ include "keycloak-extensions.keycloak.connection.authUrl" . | quote }}
  KC_USER: {{ include "keycloak-extensions.keycloak.auth.username" . | quote }}
  KC_REALM:  {{ include "keycloak-extensions.keycloak.auth.realm" . | quote }}
  KC_USER_REALM: {{ include "keycloak-extensions.keycloak.auth.masterRealm" . | quote }}
  POSTGRES_HOST: {{ include "keycloak-extensions.postgresql.connection.host" . | quote }}
  POSTGRES_PORT: {{ include "keycloak-extensions.postgresql.connection.port" . | quote }}
  POSTGRES_USER: {{ include "keycloak-extensions.postgresql.auth.username" . | quote }}
  POSTGRES_DATABASE_NAME: {{ include "keycloak-extensions.postgresql.auth.database" . | quote }}
  CAPTCHA_SITE_KEY: "{{ .Values.proxy.appConfig.captchaSiteKey }}"
  CAPTCHA_SECRET_KEY: "{{ .Values.proxy.appConfig.captchaSecretKey }}"
  LOG_LEVEL: "{{ .Values.proxy.appConfig.logLevel }}"
