# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-handler" (include "common.names.fullname" .) }}
  labels:
      {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
      {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-handler" (include "common.names.fullname" .)) }}
      {{- $mergedLabels := merge $uiLabels $commonLabels }}
      {{- toYaml $mergedLabels | nindent 4 }}
  {{- if .Values.handler.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.handler.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.handler.replicaCount }}
  selector:
    matchLabels:
      {{- $commonLabels := include "common.labels.matchLabels" . | fromYaml }}
      {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-handler" (include "common.names.fullname" .)) }}
      {{- merge $uiLabels $commonLabels | toYaml | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-handler.yaml") . | sha256sum }}
        {{- with .Values.handler.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
        {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-handler" (include "common.names.fullname" .)) }}
        {{- $mergedLabels := merge $uiLabels $commonLabels }}
        {{- toYaml $mergedLabels | nindent 8 }}
    spec:
      {{- with .Values.handler.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.handler.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.handler.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.handler.podSecurityContext }}
      securityContext:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- if or .Values.handler.imagePullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- if .Values.handler.imagePullSecrets }}
        {{- range .Values.handler.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- else if .Values.global.imagePullSecrets }}
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.handler.serviceAccount.create }}
      serviceAccountName: {{ printf "%s-handler" (include "common.names.fullname" .) }}
      {{- end }}
      {{- if .Values.handler.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.handler.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: "keycloak-bfp-handler"
          securityContext:
            {{- toYaml .Values.handler.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry | default .Values.handler.image.registry }}/{{ .Values.handler.image.repository }}{{ if .Values.handler.image.sha256 }}@sha256:{{ .Values.handler.image.sha256 }}{{ else }}:{{ .Values.handler.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default .Values.handler.image.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-handler" (include "common.names.fullname" .) }}
          env:
            - name: KC_USER
              value: {{ tpl .Values.keycloak.auth.username . }}
            - name: KC_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.keycloak.auth.existingSecret.name . }}
                  key: {{ include "common.secrets.key" (dict "existingSecret" .Values.keycloak.auth.existingSecret "key" "adminPassword") | quote }}
            - name: POSTGRES_USER
              value: {{ tpl .Values.postgresql.auth.username . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.postgresql.auth.existingSecret.name . }}
                  key: {{ include "common.secrets.key" (dict "existingSecret" .Values.postgresql.auth.existingSecret "key" "password") | quote }}
            - name: SMTP_USERNAME
              value: {{ tpl .Values.smtp.auth.username . }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.smtp.auth.existingSecret.name . }}
                  key: {{ include "common.secrets.key" (dict "existingSecret" .Values.smtp.auth.existingSecret "key" "password") | quote }}
          {{- if .Values.handler.service.ports }}
          ports:
            {{- range $key, $value := .Values.handler.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.handler.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.handler.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.handler.livenessProbe.enabled }}
          livenessProbe:
            exec:
              - /bin/bash
              - -c
              - |
                {{- .Values.handler.livenessProbe.command | nindent 16 }}
            initialDelaySeconds: {{ .Values.handler.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.handler.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.handler.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.handler.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.handler.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.handler.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.handler.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.handler.readinessProbe.enabled }}
          readinessProbe:
            exec:
              - /bin/bash
              - -c
              - |
                {{- .Values.handler.readinessProbe.command | nindent 16 }}
            initialDelaySeconds: {{ .Values.handler.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.handler.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.handler.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.handler.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.handler.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.handler.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.handler.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.handler.startupProbe.enabled }}
          startupProbe:
            exec:
              - /bin/bash
              - -c
              - |
                {{- .Values.handler.startupProbe.command | nindent 16 }}
            initialDelaySeconds: {{ .Values.handler.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.handler.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.handler.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.handler.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.handler.startupProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.handler.resources | nindent 12 }}
          {{- if .Values.handler.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.handler.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
