# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- if .Values.proxy.ingress.enabled -}}
---

apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ printf "%s-proxy" (include "common.names.fullname" .) }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
  "values" ( list .Values.additionalAnnotations .Values.proxy.ingress.annotations )
  "context" . )
  | nindent 2 }}
    {{- if .Values.proxy.ingress.certManager.enabled }}
    cert-manager.io/{{ .Values.proxy.ingress.certManager.issuerRef.kind | kebabcase }}: "{{ coalesce .Values.global.certManagerIssuer .Values.proxy.ingress.certManager.issuerRef.name }}"
    {{- end }}
spec:
  {{- if or .Values.proxy.ingress.ingressClassName .Values.global.ingressClass }}
  ingressClassName: {{ coalesce .Values.proxy.ingress.ingressClassName .Values.global.ingressClass | quote }}
  {{- end }}
  {{- if .Values.proxy.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ include "keycloak-extensions.ingress.proxy.host" . | quote }}
      secretName: {{ include "keycloak-extensions.ingress.proxy.tls.secretName" . | quote }}
  {{- end }}
  rules:
    - host: {{ include "keycloak-extensions.ingress.proxy.host" . | quote }}
      http:
        paths:
          {{- range .Values.proxy.ingress.paths }}
          - pathType: {{ .pathType }}
            path: {{ .path }}
            {{- if .backend }}
            backend: {{- (toYaml .backend) | nindent 14 }}
            {{- else }}
            backend: {{- default (include "common.ingress.backend" (dict "serviceName" (printf "%s-proxy" (include "common.names.fullname" $)) "servicePort" "http" "context" $)) | nindent 14 }}
            {{- end }}
          {{- end }}

...
{{- end }}
