# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- if .Values.proxy.ingress.enabled -}}
---

apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ printf "%s-proxy" (include "common.names.fullname" .) }}
  labels:
    {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-proxy" (include "common.names.fullname" .)) }}
    {{- $mergedLabels := merge $uiLabels $commonLabels}}
    {{- toYaml $mergedLabels | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ include "keycloak-extensions.ingress.certManagerIssuer" . | quote }}
    nginx.org/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
  {{- with .Values.proxy.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ include "keycloak-extensions.ingress.ingressClassName" . }}
  {{- if .Values.proxy.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ include "keycloak-extensions.ingress.proxy.host" . | quote }}
      secretName: {{ include "keycloak-extensions.ingress.proxy.tls.secretName" . | quote }}
  {{- end }}
  rules:
    - host: {{ include "keycloak-extensions.ingress.proxy.host" . | quote }}
      http:
        paths:
          {{- range .Values.proxy.ingress.paths }}
          - pathType: {{ .pathType }}
            path: {{ .path }}
            {{- if .backend }}
            backend: {{- (toYaml .backend) | nindent 14 }}
            {{- else }}
            backend: {{- default (include "common.ingress.backend" (dict "serviceName" (printf "%s-proxy" (include "common.names.fullname" $)) "servicePort" "http" "context" $)) | nindent 14 }}
            {{- end }}
          {{- end }}

...
{{- end }}
