# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- if .Values.handler.ingress.enabled -}}
---

apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ printf "%s-handler" (include "common.names.fullname" .) }}
  labels:
    {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-handler" (include "common.names.fullname" .)) }}
    {{- $mergedLabels := merge $uiLabels $commonLabels }}
    {{- toYaml $mergedLabels | nindent 4 }}
  annotations:
    {{- with .Values.handler.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.handler.ingress.certManager.enabled }}
    cert-manager.io/{{ .Values.handler.ingress.certManager.issuerRef.kind | kebabcase }}: "{{ coalesce .Values.global.certManagerIssuer .Values.handler.ingress.certManager.issuerRef.name }}"
    {{- end }}
spec:
  {{- if or .Values.handler.ingress.ingressClassName .Values.global.ingressClass }}
  ingressClassName: {{ coalesce .Values.handler.ingress.ingressClassName .Values.global.ingressClass | quote }}
  {{- end }}
  {{- if .Values.handler.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.handler.ingress.host | quote }}
      secretName: "{{ .Values.handler.ingress.tls.secretName }}"
  {{- end }}
  rules:
    - host: {{ .Values.handler.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.handler.ingress.paths }}
          - pathType: {{ .pathType }}
            path: {{ .path }}
            {{- if .backend }}
            backend: {{- (toYaml .backend) | nindent 14 }}
            {{- else }}
            backend: {{- default (include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "http" "context" $)) | nindent 14 }}
            {{- end }}
          {{- end }}

...
{{- end }}
