# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only


{{- if .Values.smtp.auth.enabled }}
{{- $_ := required "An smtp password is required, see parameter smtp.auth." (coalesce .Values.smtp.auth.password (.Values.smtp.auth.existingSecret).name) }}
{{- if not (.Values.smtp.auth.existingSecret).name }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "smtp-credentials" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  password: {{ .Values.smtp.auth.password | quote }}
{{- end }}
{{- end }}
