{{/*
SPDX-FileCopyrightText: 2024 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
{{- if .Values.handler.serviceAccount.create }}
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: {{ printf "%s-handler" (include "common.names.fullname" .) }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.handler.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.handler.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.handler.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.handler.serviceAccount.annotations "context" . ) | nindent 4 }}
    {{- end }}
    {{- if .Values.handler.additionalAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.handler.additionalAnnotations "context" . ) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.handler.serviceAccount.automountServiceAccountToken }}
...
{{- end }}
