---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-handler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-handler
    spec:
      containers:
        - name: handler
          image: {{ tpl .Values.handler.image . }}
          env:
            - name: KC_AUTH_URL
              value: "http://{{ tpl .Values.keycloak.serviceName . }}/admin"
            - name: KC_USER
              value: {{ .Values.keycloak.adminUsername }}
            - name: KC_PASS
              value: {{ .Values.keycloak.adminPassword }}
            - name: KC_REALM
              value: {{ .Values.handler.kcRealm }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DATABASE_NAME
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_HOST
              value: {{ template "postgres.fullname" . }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: LOG_LEVEL
              value: {{ .Values.handler.logLevel }}
            - name: FAILED_ATTEMPTS_FOR_IP_BLOCK
              value: "{{ .Values.handler.failedAttemptsForIpBlock }}"
            - name: FAILED_ATTEMPTS_FOR_DEVICE_BLOCK
              value: "{{ .Values.handler.failedAttemptsForDeviceBlock }}"
            - name: FAILED_ATTEMPTS_FOR_CAPTCHA_TRIGGER
              value: "{{ .Values.handler.failedAttemptsForCaptchaTrigger }}"
            - name: EVENTS_RETENTION_PERIOD
              value: "{{ .Values.handler.eventsRetentionPeriod }}"
            - name: AUTO_EXPIRE_RULE_IN_MINS
              value: "{{ .Values.handler.autoExpireRuleInMins }}"
            - name: DEVICE_PROTECTION_ENABLE
              value: "{{ .Values.handler.deviceProtectionEnable }}"
            - name: IP_PROTECTION_ENABLE
              value: "{{ .Values.handler.ipProtectionEnable }}"
            - name: CAPTCHA_PROTECTION_ENABLE
              value: "{{ .Values.handler.captchaProtectionEnable }}"
      imagePullSecrets:
        - name: uv-registry
