---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.fullname" . }}
spec:
  selector:
    app: {{ template "postgres.fullname" . }}
  ports:
    - name: db
      port: 5432
      targetPort: 5432
  type: ClusterIP
