---

apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  ports:
    - name: http
      port: 8181
      targetPort: 8181
  type: ClusterIP
