# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
# Default values for keycloak-bfp-handler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []

# -- Application configuration of the Handler
appConfig:
  # -- Application LOG level: `DEBUG`, `INFO`, `WARN` or `ERROR`
  logLevel: "DEBUG"
  # -- Number of failed login attempts within the minutes of `EVENTS_RETENTION_MINUTES` to trigger an IP block. Should be grater than `FAILED_ATTEMPTS_FOR_DEVICE_BLOCK` if it is enabled
  failedAttemptsForIpBlock: 7
  # -- Number of failed login attempts within the minutes of `EVENTS_RETENTION_MINUTES` to trigger a device block. Should be greater than `FAILED_ATTEMPTS_FOR_CAPTCHA_TRIGGER` if it is enabled
  failedAttemptsForDeviceBlock: 5
  # -- Number of failed login attempts within the minutes of `EVENTS_RETENTION_MINUTES` to enforce reCaptcha prompt
  failedAttemptsForCaptchaTrigger: 3
  # -- Minutes to buffer Keycloak events locally, allowing to persist more than the configured in Keycloak
  eventsRetentionPeriod: 10
  # -- Minutes to automatically expire actions such as IP and device blocks and reCaptcha prompt
  autoExpireRuleInMins: 5
  # -- Whether to enable device blocking
  deviceProtectionEnable: "True"
  # -- Whether to enable IP blocking
  ipProtectionEnable: "True"
  # -- Whether to enable reCaptcha prompting protection
  captchaProtectionEnable: "True"
  # -- Email SMTP hostname
  smtpHost: "mail.example.org"
  # -- Email SMTP port
  smtpPort: "587"
  # -- Username for SMTP authentication
  smtpUsername: "univention"
  # -- Password for SMTP authentication
  smtpPassword: "some_password"
  # -- Email to send emails from
  mailFrom: "univention@example.org"
  # -- Subject for email notification to users on New Device Login
  newDeviceLoginSubject: "New device login"

# -- Global Keycloak Extensions configuration values
global:
  # -- External Keycloak global settings
  keycloak:
    # -- Host where keycloak is accessible (specify port if needed)
    host: "sso.example.com"
    # -- Admin user for Keycloak admin-cli
    adminUsername: "admin"
    # -- Admin password for Keycloak admin-cli provided user
    adminPassword: "univention"
    # -- Keycloak realm to listen events on (master allows to listen for all realms)
    realm: "ucs"
    adminRealm:
  # -- PostgreSQL global settings
  postgresql:
    connection:
      # -- Hostname or IP address of the server hosting the PostgreSQL database
      host: "keycloak-extensions-postgresql"
      # -- Port number that the PostgreSQL database is exposed on
      port: "5432"
    auth:
      # -- Database for the proxy and handler to use
      database: "bfp"
      # -- User for the PostgreSQL database
      username: "bfp"
      # -- Password for the PostgreSQL database
      password: "correcthorsebatterystaple"

# -- Kubernetes ingress
ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: false

## Docker image
image:
  registry: "registry.souvap-univention.de"
  repository: "souvap/tooling/images/keycloak-extensions/keycloak-handler"
  tag: "0.1.0"
  imagePullPolicy: "Always"

# -- Credentials to fetch images from private registry.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
#
# imagePullSecrets:
#   - "docker-registry"
imagePullSecrets: []

## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

## Deployment resources
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "4Gi"
    cpu: "4"

## Kubernetes service
service:
  enabled: false
