stages:
  - build
  - upload
  - release

# Job dependencies
include:
  - local: "/.gitlab/ci/maven_jobs.yml"
  - local: "/.gitlab/ci/theme_jobs.yml"

# Global pipeline variables
variables:
  PACKAGE_NAME: "reCaptcha-auth-flow"
  PACKAGE_REGISTRY_URL_BASE: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}"

# Uploads the theme and jar artifacts as a generic package.
# From: https://gitlab.com/gitlab-org/release-cli/-/tree/master/docs/examples/release-assets-as-generic-package/
upload:
  stage: upload
  image: "curlimages/curl:latest"
  needs:
    - "retrieve_maven_version"
    - "maven_clean_install"
    - "archive_theme_files"
  variables:
    PACKAGE_REGISTRY_URL: "${PACKAGE_REGISTRY_URL_BASE}/${MAVEN_PROJECT_VERSION}"
  script:
    - ls -la
    - >
      curl
      --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
      --upload-file reCaptcha-theme.tar.gz
      "$PACKAGE_REGISTRY_URL/${PACKAGE_NAME}-theme.tar.gz"
    - >
      curl
      --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
      --upload-file reCaptcha-auth-flow.jar
      "$PACKAGE_REGISTRY_URL/${PACKAGE_NAME}-plugin.jar"

# Creates a Gitlab release with the appropriate versioned release tag, and attached artifacts.
release_version_package:
  stage: release
  image: "registry.gitlab.com/gitlab-org/release-cli:latest"
  needs:
    - "retrieve_maven_version"
    - "upload"
  variables:
    PACKAGE_REGISTRY_URL: "${PACKAGE_REGISTRY_URL_BASE}/${MAVEN_PROJECT_VERSION}"
  script:
    - 'echo "Running release job for: $MAVEN_PROJECT_VERSION"'
    - >
      release-cli
      create
      --name "KeyCloak reCaptcha Auth-Flow Plugin (v$MAVEN_PROJECT_VERSION)"
      --tag-name "release-v$MAVEN_PROJECT_VERSION"
      --assets-link "{\"name\":\"reCaptcha-theme.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}-theme.tar.gz\"}"
      --assets-link "{\"name\":\"reCaptcha-auth-flow.jar\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}-plugin.jar\"}"
