---
stages:
  - build
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/reCaptcha-auth-flow/${VERSION_TAG}"

include:
  - local: "/.gitlab/ci/plugin_pipeline.yml"
  - local: "/.gitlab/ci/theme_pipeline.yml"

# This uploads the built artifacts to the GitLab registry as a generic package.
# Taken from: https://gitlab.com/gitlab-org/release-cli/-/tree/master/docs/examples/release-assets-as-generic-package/
upload:
  stage: upload
  image: "curlimages/curl:latest"
  needs:
    - "maven_clean_install"
    - "archive_theme_files"
  script:
    - >
      curl
      --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
      --upload-file "$FILENAME_RECAPTCHA_PLUGIN_THEME"
      "$PACKAGE_REGISTRY_URL/$FILENAME_RECAPTCHA_PLUGIN_THEME"
    - >
      curl
      --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
      --upload-file "$FILENAME_RECAPTCHA_PLUGIN_JAR"
      "$PACKAGE_REGISTRY_URL/$FILENAME_RECAPTCHA_PLUGIN_JAR"

# The Release Job is triggered manually.
# This happens in the Gitlab CI pipeline web UI.
release_version_package:
  stage: release
  image: "registry.gitlab.com/gitlab-org/release-cli:latest"
  variables:
    VERSION_TAG: "v$MAVEN_PROJECT_VERSION"
  script:
    - 'echo "Running release job for: $VERSION_TAG"'
  release:
    tag_name: "$VERSION_TAG"
    name: 'KeyCloak reCaptcha Auth-Flow Plugin ($VERSION_TAG)'
    description: 'JAR file and theme archive for the KeyCloak reCaptcha Auth-Flow plugin.'
  needs:
    - "upload"