---
stages:
  - upload
  - release

workflow:
  rules:
    - if: '$CI_COMMIT_TAG != null'
      variables:
        VERSION_TAG: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_TAG == null'
      variables:
        VERSION_TAG: $CI_COMMIT_SHORT_SHA

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/myawesomerelease/${PACKAGE_VERSION}"

# This uploads the built artifacts to the GitLab registry as a generic package.
# Taken from: https://gitlab.com/gitlab-org/release-cli/-/tree/master/docs/examples/release-assets-as-generic-package/
upload:
  stage: upload
  image: "curlimages/curl:latest"
  needs:
    - pipeline: $UPSTREAM_PIPELINE_ID
      job: "build_jar"
      artifacts: true
    - pipeline: $UPSTREAM_PIPELINE_ID
      job: "build_theme"
      artifacts: true
  script:
    - ls -la
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "reCaptcha-theme.tar.gz $PACKAGE_REGISTRY_URL/reCaptcha-theme.tar.gz"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file reCaptcha-auth-flow/target/reCaptcha-auth-flow.jar $PACKAGE_REGISTRY_URL/reCaptcha-auth-flow/target/reCaptcha-auth-flow.jar

# The Release Job is triggered manually.
# This happens in the Gitlab CI pipeline web UI.
release_version_package:
  stage: release
  image: "registry.gitlab.com/gitlab-org/release-cli:latest"
  script:
    - 'echo "Running release job for: $VERSION_TAG"'
  release:
    tag_name: $VERSION_TAG
    name: 'Release $VERSION_TAG'
    description: 'Release created using the release-cli.'
  needs:
    - upload