# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH
---

handler:
  replicaCount: 42

proxy:
  replicaCount: 42
  ingress:
    ingressClassName: "kyverno"
    tls:
      secretName: "kyverno-tls"
